export const userData = [
  {
    name: "Jan",
    "Active User": 4000,
    "Mute User": 2400,
    "User Run": 2400,
  },
  {
    name: "Feb",
    "Active User": 3000,
    "Mute User": 1398,
    "User Run": 2210,
  },
  {
    name: "Mar",
    "Active User": 2000,
    "Mute User": 9800,
    "User Run": 2290,
  },
  {
    name: "Apr",
    "Active User": 2780,
    "Mute User": 3908,
    "User Run": 2000,
  },
  {
    name: "Mei",
    "Active User": 1890,
    "Mute User": 4800,
    "User Run": 2181,
  },
  {
    name: "Jun",
    "Active User": 2390,
    "Mute User": 3800,
    "User Run": 2500,
  },
  {
    name: "Jul",
    "Active User": 1,
    "Mute User": 4300,
    "User Run": 2100,
  },
  {
    name: "Agt",
    "Active User": 1,
    "Mute User": 4300,
    "User Run": 2100,
  },
  {
    name: "Sep",
    "Active User": 1,
    "Mute User": 4300,
    "User Run": 2100,
  },
  {
    name: "Okt",
    "Active User": 1,
    "Mute User": 4300,
    "User Run": 2100,
  },
  {
    name: "Nov",
    "Active User": 1,
    "Mute User": 4300,
    "User Run": 2100,
  },
  {
    name: "Des",
    "Active User": 1,
    "Mute User": 4300,
    "User Run": 2100,
  },
];

export const userRows = [
  {
    id: 1,
    username: "Raodatul Aini",
    avatar: "https://drive.google.com/uc?id=1-QKAnXgL4WlM095s1U9zVhQ-X1PRCn8F",
    email: "raodatul@gmail.com",
    status: "active",
    transaction: "Rp.9000000",
  },
  {
    id: 2,
    username: "Dewi Putri",
    avatar: "https://drive.google.com/uc?id=1G9kuSb-wv5sRFa8UbYG96kop5TVR1lT_",
    email: "alikanaila@yahoo.com",
    status: "active",
    transaction: "Rp.7000000",
  },
  {
    id: 3,
    username: "Emha Asqolani",
    avatar: "https://drive.google.com/uc?id=1u1zwrG6PxI5O3JI3nIREYWvDgRoXcOlm",
    email: "emha@drive.com",
    status: "active",
    transaction: "Rp.6000000",
  },
  {
    id: 4,
    username: "Ermawati Setia Ningsih",
    avatar: "https://drive.google.com/uc?id=1pf_x1YkvjEEjW1vnsvfXVTg0eKpplEiM",
    email: "emabahtiar@juju.com",
    status: "active",
    transaction: "Rp.8000000",
  },
  {
    id: 5,
    username: "M Rizal Umamy Fajri.S.Kom",
    avatar: "https://drive.google.com/uc?id=1cpB8dykw6dA1dd7klkPt7yxlbGCO843-",
    email: "umamyfajri@bilibili",
    status: "active",
    transaction: "Rp.8564434",
  },
];
