export const userData = [
  {
    name: "Jan",
    "Active User": 4000,
    "Mute User": 2400,
    "User Run": 2400,
  },
  {
    name: "Feb",
    "Active User": 3000,
    "Mute User": 1398,
    "User Run": 2210,
  },
  {
    name: "Mar",
    "Active User": 2000,
    "Mute User": 9800,
    "User Run": 2290,
  },
  {
    name: "Apr",
    "Active User": 2780,
    "Mute User": 3908,
    "User Run": 2000,
  },
  {
    name: "Mei",
    "Active User": 1890,
    "Mute User": 4800,
    "User Run": 2181,
  },
  {
    name: "Jun",
    "Active User": 2390,
    "Mute User": 3800,
    "User Run": 2500,
  },
  {
    name: "Jul",
    "Active User": 1,
    "Mute User": 4300,
    "User Run": 2100,
  },
  {
    name: "Agt",
    "Active User": 1,
    "Mute User": 4300,
    "User Run": 2100,
  },
  {
    name: "Sep",
    "Active User": 1,
    "Mute User": 4300,
    "User Run": 2100,
  },
  {
    name: "Okt",
    "Active User": 1,
    "Mute User": 4300,
    "User Run": 2100,
  },
  {
    name: "Nov",
    "Active User": 1,
    "Mute User": 4300,
    "User Run": 2100,
  },
  {
    name: "Des",
    "Active User": 1,
    "Mute User": 4300,
    "User Run": 2100,
  },
];

export const productData = [
  {
    name: "Jan",
    Sales: 4234,
    Sales2: 2342,
    Sales3: 2342,
  },
  {
    name: "Feb",
    Sales: 5454,
    Sales2: 5675,
    Sales3: 8654,
  },
  {
    name: "Mar",
    Sales: 2424,
    Sales2: 5466,
    Sales3: 5643,
  },
];

export const userRows = [
  {
    id: 1,
    username: "Raodatul Aini",
    avatar: "https://drive.google.com/uc?id=1-QKAnXgL4WlM095s1U9zVhQ-X1PRCn8F",
    email: "raodatul@gmail.com",
    status: "active",
    transaction: "Rp.9000000",
  },
  {
    id: 2,
    username: "Dewi Putri",
    avatar: "https://drive.google.com/uc?id=1G9kuSb-wv5sRFa8UbYG96kop5TVR1lT_",
    email: "alikanaila@yahoo.com",
    status: "active",
    transaction: "Rp.7000000",
  },
  {
    id: 3,
    username: "Emha Asqolani",
    avatar: "https://drive.google.com/uc?id=1u1zwrG6PxI5O3JI3nIREYWvDgRoXcOlm",
    email: "emha@drive.com",
    status: "active",
    transaction: "Rp.6000000",
  },
  {
    id: 4,
    username: "Ermawati Setia Ningsih",
    avatar: "https://drive.google.com/uc?id=1pf_x1YkvjEEjW1vnsvfXVTg0eKpplEiM",
    email: "emabahtiar@juju.com",
    status: "active",
    transaction: "Rp.8000000",
  },
  {
    id: 5,
    username: "M Rizal Umamy Fajri.S.Kom",
    avatar: "https://drive.google.com/uc?id=1cpB8dykw6dA1dd7klkPt7yxlbGCO843-",
    email: "umamyfajri@bilibili",
    status: "active",
    transaction: "Rp.8564434",
  },
];

export const productRows = [
  {
    id: 1,
    name: "Genteng Seng Kasar",
    img: "https://drive.google.com/uc?id=1wdirquTbKL-jx9Azzo_sm3PzKGxrTF0r",
    stock: 23,
    status: "active",
    price: "Rp.1000",
  },
  {
    id: 2,
    name: "Kalitemu Super",
    img: "https://drive.google.com/uc?id=1YAWjnP64nnRO54MU8ypgzcBBgEXUo3Qh",
    stock: 13,
    status: "active",
    price: "Rp.2000",
  },
  {
    id: 3,
    name: "Asbes Halus",
    img: "https://drive.google.com/uc?id=1NGblvJ2BBBnTvUrNnaAmXLkyp1iZGst3",
    stock: 12,
    status: "active",
    price: "Rp.3000",
  },
  {
    id: 4,
    name: "Buwung Lepang",
    img: "https://drive.google.com/uc?id=1Oz7ZBv6UKxrlDst8y6ChKIoJr3mzF43V",
    stock: 1,
    status: "active",
    price: "Rp.4000",
  },
  {
    id: 5,
    name: "Pejaten XL",
    img: "https://drive.google.com/uc?id=12wbr82MVukJ135CPWPhlxrgKExZ8mzoW",
    stock: 3,
    status: "active",
    price: "Rp.5000",
  },
  {
    id: 6,
    name: "Buwung Bintang",
    img: "https://drive.google.com/uc?id=1ZT6dTGFdwj5h4XCz8NtHGPEDGuvglvnB",
    stock: 1,
    status: "active",
    price: "Rp.8000",
  },
  {
    id: 7,
    name: "Genteng Semen",
    img: "https://drive.google.com/uc?id=1gGRxCG-OGikVm4bdwqZpQoiFIFI2qv4a",
    stock: 23,
    status: "active",
    price: "Rp.9000",
  },
  {
    id: 8,
    name: "Kalitemu Super XL",
    img: "https://drive.google.com/uc?id=1MR-yMV5D89d1pr0oIraJWSP4MEqN1BNn",
    stock: 13,
    status: "active",
    price: "Rp.10000",
  },
];
